<?php

/**
 * Implements hook_islandora_basic_collection_query_backends().
 */
function islandora_collection_sort_islandora_basic_collection_query_backends() {
  $module_path = drupal_get_path('module', 'islandora_collection_sort');
  return array(
    'islandora_collection_sort_query_backend' => array(
      'title' => t('Natural sort (cached)'),
      'callable' => 'islandora_collection_sort_islandora_basic_collection_backend_callable',
      'file' => "$module_path/includes/utilities.inc",
    ),
  );
}

function islandora_collection_sort_islandora_object_ingested(AbstractObject $object) {
  module_load_include('inc', 'islandora_collection_sort', 'includes/utilities');
  $parents = $object->relationships->get(FEDORA_RELS_EXT_URI, 'isMemberOfCollection');
  foreach ($parents as $parent) {
    clear_collection_counts_cache($parent['object']['value']);
  }
}

function islandora_collection_sort_islandora_object_modified(AbstractObject $object) {
  module_load_include('inc', 'islandora_collection_sort', 'includes/utilities');
  $parents = $object->relationships->get(FEDORA_RELS_EXT_URI, 'isMemberOfCollection');
  foreach ($parents as $parent) {
    clear_collection_counts_cache($parent['object']['value']);
  }
}

function islandora_collection_sort_islandora_datastream_ingested(AbstractObject $object) {
  module_load_include('inc', 'islandora_collection_sort', 'includes/utilities');
  $parents = $object->relationships->get(FEDORA_RELS_EXT_URI, 'isMemberOfCollection');
  foreach ($parents as $parent) {
    clear_collection_counts_cache($parent['object']['value']);
  }
}